### PR TITLE
Issue #262: Creating elements with a checked:false attribute wrongly checks the new element in some browsers

### PR DESCRIPTION
**Pull request by sdumitriu**
Fixed.

This is a regression introduced by 4a22a52e08fce7dfe95bf54b8f52314614ee24b3

### CODE REVIEW

**Comment by savetheclocktower** [comment]
Can you give me a failing test case? I don't know which browsers this is failing in and can't get my own test case to fail.

**Comment by sdumitriu** [comment]
According to [@Deses' comment](https://github.com/sstephenson/prototype/commit/4a22a52e08fce7dfe95bf54b8f52314614ee24b3#commitcomment-7555020), IE8 and Chrome 36.

**Comment by savetheclocktower** [comment]
Oh, right. That was this… thing.

I'm conflicted because the existing code looks wrong, but ends up working correctly for slapstick reasons. This PR looks better, but ends up doing twice as much work. For instance, `someNode.writeAttribute('style', 'border: 0');` would first set `someNode.style.cssText` to `border: 0` (the proper thing to do) and then would call `someNode.setAttribute('style', 'border: 0')`, which is the very thing we're trying to avoid.

Since the current code sets `name` to `undefined` in such a case, it ends up not doing any damage when it eventually calls `setAttribute`.

I have a better fix, but no way of testing it, because I can't reproduce the problem. JavaScript is fun.

**Comment by savetheclocktower** [comment]
We'll see how this fix goes! Tests pass in all browsers, at least. Thanks for the help.

**Pull request closed without merging**
